[target.xtensa-esp32-none-elf]
runner = "espflash flash --chip esp32 --port COM1 --monitor"

[env]
ESP_LOG="INFO"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
